### ISSUE TITLE
Exception in thread "Craft Scheduler Thread"

### ISSUE THREAD

**Issue by TiTo-418** [zDevelopers/UHPlugin#130]
#### Environment

* **Minecraft version**: 1.8.8
* **Plateform used**: Spigot
* **Bukkit or Spigot version**: http://prntscr.com/azcba2
* **Plugin version**: http://jenkins.carrade.eu/job/UltraHardcoreReloaded/299/
* **Plugin build number**: 441eed1186f770b2dd9105ab2de0948314ac65c4 - construction 299

#### Problem description

It just spams the console with this error and the scoreboard doesn't work:

```
[07:08:34 WARN]: Exception in thread "Craft Scheduler Thread - 48"
[07:08:34 WARN]: org.apache.commons.lang.UnhandledException: Plugin UHPlugin v1.3 ºcdev generated an exception while executing task 6
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at eu.carrade.amaury.UHCReloaded.scoreboard.GameSidebar.preRender(GameSidebar.java:184)
        at me.azenet.UHPlugin.components.scoreboard.Sidebar.refresh(Sidebar.java:277)
        at me.azenet.UHPlugin.components.scoreboard.Sidebar$1.run(Sidebar.java:342)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

#### Steps to reproduce

/uh spawns generate random
/uh start

**Comment by TiTo-418** [comment]
I found the source

```
episodes:
    enabled: false
```

**Comment by AmauryCarrade** [comment]
Fixed, thanks for reporting!
