### ISSUE TITLE
config.yml

### ISSUE THREAD

**Issue by hamaadasif** [zDevelopers/UHPlugin#152]
1.8 
Windows 10: CraftBukkit
Bukkit
Latest

cannot load config.yml
[16:17:27 INFO]: [UHPlugin] Enabling UHPlugin v1.4
[16:17:27 ERROR]: Cannot load plugins\UHPlugin\config.yml
org.bukkit.configuration.InvalidConfigurationException: expected '<document start>', but found BlockMappingStart
 in 'string', line 16, column 1:
    lang:
    ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:188) [craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:162) [craftbukkit.jar:git-Bukkit-33d5de3]
        at eu.carrade.amaury.UHCReloaded.zlib.components.configuration.Configuration.init(Configuration.java:50) [UHCReloaded-1.4.jar:?]
        at eu.carrade.amaury.UHCReloaded.zlib.components.configuration.Configuration.onEnable(Configuration.java:45) [UHCReloaded-1.4.jar:?]
        at eu.carrade.amaury.UHCReloaded.zlib.core.ZLibComponent.setEnabled(ZLibComponent.java:68) [UHCReloaded-1.4.jar:?]
        at eu.carrade.amaury.UHCReloaded.zlib.core.ZLib.loadComponent(ZLib.java:98) [UHCReloaded-1.4.jar:?]
        at eu.carrade.amaury.UHCReloaded.zlib.core.ZLib.loadComponent(ZLib.java:120) [UHCReloaded-1.4.jar:?]
        at eu.carrade.amaury.UHCReloaded.zlib.core.ZPlugin.loadComponents(ZPlugin.java:64) [UHCReloaded-1.4.jar:?]
        at eu.carrade.amaury.UHCReloaded.UHCReloaded.onEnable(UHCReloaded.java:107) [UHCReloaded-1.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) [craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) [craftbukkit.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) [craftbukkit.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) [craftbukkit.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit.jar:git-Bukkit-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: org.yaml.snakeyaml.parser.ParserException: expected '<document start>', but found BlockMappingStart
 in 'string', line 16, column 1:
    lang:
    ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:225) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:400) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        ... 23 more

Anyone know how to fix?

**Comment by Vlammar** [comment]
This looks like a spacing issue, check if you haven't put an extra space
